name: NoDreams
version: ${project.version}
main: nodream.nodream.NoDreams
api-version: 1.13
description: Better dreams and no phantoms

commands:
  nodreams:
    permission: nodreams
    usage: /nodreams
    permission-message: You are not allowed to use this command.
